<?php
/**
 * Created by PhpStorm.
 * User: adamgrabek
 * Date: 19/06/15
 * Time: 13:32
 */

namespace Famillio\Domain\Family\Collection\Biography\DataExtractor\Name;


use Famillio\Domain\Family\Collection\Biography\DataExtractor\DataExtractorAggregate;
use Famillio\Domain\Family\Collection\Biography\DataExtractor\DataExtractorInterface;

/**
 * Class FullName
 *
 * @package Famillio\Domain\Family\Collection\Biography\DataExtractor\Name
 */
class FullName extends DataExtractorAggregate
{
    public function __construct(array $extractors)
    {
        parent::__construct($extractors); // TODO: Change the autogenerated stub
    }

    public function registerExtractor(DataExtractorInterface $dataExtractorInterface)
    {
        parent::registerExtractor($dataExtractorInterface); // TODO: Change the autogenerated stub
    }

    public function data() : ValueObjectInterface
    {
        parent::data(); // TODO: Change the autogenerated stub
    }

}